apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graph-pvc
  labels:
    name: graph-pvc
spec:
  accessModes:
   - ReadWriteOnce
  resources:  
    requests:
      storage: 500Mi