apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc1
  labels:
    name: prom_pvc
spec:
  accessModes:
   - ReadWriteOnce
  resources:  
    requests:
      storage: 500Mi